# Importing Libraries

In [375]:
import numpy as np
import pandas as pd


In [376]:
data=pd.read_csv(r"C:\Users\aravindv\Documents\Github-projects\ML_PredictionsinHTML\Heart_Attack_Prediction\heart.csv")
data

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [377]:
data.info()#basic idea that we get from the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trtbps    303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalachh  303 non-null    int64  
 8   exng      303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64  
 11  caa       303 non-null    int64  
 12  thall     303 non-null    int64  
 13  output    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [378]:
data.describe()#statistical analysis

age         sex          cp      trtbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg    thalachh        exng     oldpeak         slp         caa  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

            thall      output  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

### Dividing the Dataset into Depedent and Independent Columns

In [379]:
X=data.drop(['output'],axis=1) #independent features from the dataset
y=data['output'] #dependent column from the dataset
X

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  
0      0      1  
1      0      2  
2      0      2  
3      0      2  
4      0      2  
..   ...    ...  
298    0      3  
299    0      3  
300    2      3  
301    1      3  
302    1      2  

[303 rows x 13 columns]

In [380]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

### Splitting the dataset into training and testing set
#### 20% of the dataset will be used for testing(evaluation) and 80% of the data will be used for training purposes

In [381]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

### Logistic Regression Algorithm

In [382]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()

In [383]:
logmodel.fit(X_train,y_train)

C:\Users\aravindv\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [384]:
y_pred=logmodel.predict(X_test)

In [385]:
print(y_pred)

[0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 1 0 1 0 0 0 0 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0]


In [386]:
#calculating accuracy of the Classification model
from sklearn.metrics import confusion_matrix, accuracy_score
log_cm=confusion_matrix(y_test,y_pred)
log_ac=accuracy_score(y_test,y_pred)


In [387]:
print(log_cm)

[[25  4]
 [ 3 29]]


In [388]:
print(log_ac*100)

88.52459016393442


### Decision Tree Algorithm

In [389]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier=DecisionTreeClassifier()

In [390]:
tree_classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [391]:
predictions=tree_classifier.predict(X_test)

In [392]:
from sklearn.metrics import accuracy_score,confusion_matrix
dc_cm=confusion_matrix(y_test,predictions)
dc_ac=accuracy_score(y_test,predictions)

In [393]:
print(dc_cm)

[[27  2]
 [ 7 25]]


In [394]:
print(dc_ac*100)

85.24590163934425


### KNN Algorithm

In [395]:
#importing KNN Classfier
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=11)

In [396]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [397]:
predictions=knn.predict(X_test)

In [398]:
#accuracy
from sklearn.metrics import confusion_matrix,accuracy_score
knn_cm=confusion_matrix(y_test,predictions)
knn_ac=accuracy_score(y_test,predictions)

In [399]:
print(knn_cm)

[[20  9]
 [ 6 26]]


In [400]:
print(knn_ac*100)

75.40983606557377


### Random Forest Algorithm

In [401]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [402]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [403]:
y_pred=classifier.predict(X_test)

In [404]:
from sklearn.metrics import confusion_matrix, accuracy_score
rf_cm=confusion_matrix(y_test,y_pred)
rf_ac=accuracy_score(y_test,y_pred)

In [405]:
print(rf_cm)

[[24  5]
 [ 6 26]]


In [406]:
print(rf_ac*100)

81.9672131147541


### Support Vector Machine Algorithm

In [407]:
from sklearn.svm import SVC
svc_model=SVC()

In [408]:
svc_model.fit(X_train,y_train)

SVC()

In [409]:
predictions=svc_model.predict(X_test)

In [410]:
from sklearn.metrics import confusion_matrix, accuracy_score
svm_cm=confusion_matrix(y_test,predictions)
svm_ac=accuracy_score(y_test,predictions)


In [411]:
print(svm_cm)

[[15 14]
 [ 4 28]]


In [412]:
print(svm_ac*100)

70.49180327868852


In [413]:
data


age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

### To find the Minimum and Maximum value of the dataset

In [414]:
# For Multiple columns to exclude use,
# cols = [x for x in df.columns if x not in ('mpg', 'name')]
# cols

cols = [X for X in data.columns if X not in ('output')]
cols

print("{")
for i,name in enumerate(cols):
    print(f'"{name}":{{"min":{data[name].min()},"max":{data[name].max()}}}{"," if i<(len(cols)-1) else ""}')
print("}")

{
"age":{"min":29,"max":77},
"sex":{"min":0,"max":1},
"cp":{"min":0,"max":3},
"trtbps":{"min":94,"max":200},
"chol":{"min":126,"max":564},
"fbs":{"min":0,"max":1},
"restecg":{"min":0,"max":2},
"thalachh":{"min":71,"max":202},
"exng":{"min":0,"max":1},
"oldpeak":{"min":0.0,"max":6.2},
"slp":{"min":0,"max":2},
"caa":{"min":0,"max":4},
"thall":{"min":0,"max":3}
}


In [415]:
# predictions with respect to new dataset
data_new = {'age': 30, 'sex': 0, 'cp': 3, 'trtbps': 136, 'chol': 133,
            'fbs': 0, 'restecg': 2, 'thalachh': 150, 'exng': 0, 'oldpeak': 2.3,
            'slp': 1, 'caa': 3, 'thall': 2}
index = [1]  # serial number
my_data = pd.DataFrame(data_new, index)

In [416]:
# Pricing allocated
# Here the linearmodel is the variable  used in 13
medical_details = svc_model.predict(my_data)
# rounded_price = np.round(my_data_price, 2)
print(f" The predicted price for the given data is :{medical_details}")

 The predicted price for the given data is :[1]


In [417]:
print(f"logistic regression Accuracy {log_ac*100}")
print(f"Decision Tree Accuracy {dc_ac*100}")
print(f"KNN Accuracy {knn_ac*100}")
print(f"Random Forest Accuracy {rf_ac*100}")
print(f"Support Vector Machine Accuracy {svm_ac*100}")

logistic regression Accuracy 88.52459016393442
Decision Tree Accuracy 85.24590163934425
KNN Accuracy 75.40983606557377
Random Forest Accuracy 81.9672131147541
Support Vector Machine Accuracy 70.49180327868852


In [418]:
if log_ac > dc_ac and log_ac > knn_ac and log_ac > rf_ac and log_ac > svm_ac:
    print(f"Using Algorithm : Logistic Regression with an accuracy {log_ac*100}")
elif dc_ac > log_ac and dc_ac > knn_ac and dc_ac > rf_ac and dc_ac >svm_ac:
    print(f"Using Algorithm : Decision Tree with an accuracy {dc_ac*100}")
elif knn_ac > log_ac and knn_ac > dc_ac and knn_ac > rf_ac and knn_ac > svm_ac:
    print(f"Using Algorithm :K-Nearest Neighbor with an accuracy {knn_ac*100}")
elif rf_ac > log_ac and rf_ac > dc_ac and rf_ac > knn_ac and rf_ac > svm_ac:
    print(f"Using Algorithm :Random Forest with an accuracy {rf_ac*100}")
else:
    print(f"Using Algorithm :Support Vector Machine with an accuracy {svm_ac*100}")
    
    


Using Algorithm : Logistic Regression with an accuracy 88.52459016393442
